name: e_c_g_blue_tooth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.4

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  fl_chart: 0.69.0
  syncfusion_flutter_charts: 27.1.58
  flutter_blue_plus: 1.34.5
  permission_handler: 11.3.1
  excel: 4.0.6
  path_provider: 2.1.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

